// <auto-generated />
using System;
using Cadastro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cadastro.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210911133146_Criacao")]
    partial class Criacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cadastro.Models.Veiculo", b =>
                {
                    b.Property<int>("Veiculoid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF");

                    b.Property<byte[]>("CarregarImagens");

                    b.Property<string>("NomeProprietario");

                    b.Property<string>("Placa");

                    b.Property<string>("Renavan");

                    b.HasKey("Veiculoid");

                    b.ToTable("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
